// Generated by scripts/make-responsive-images.py. Do not edit manually.
export interface ResponsiveImageMetadata { width: number; height: number; widths: readonly number[] }
export const responsiveMap: Readonly<Record<string, ResponsiveImageMetadata>> = {
  "project-01": {
    "width": 2042,
    "height": 2560,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "project-02": {
    "width": 1919,
    "height": 2560,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "project-03": {
    "width": 2042,
    "height": 2560,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "project-04": {
    "width": 2560,
    "height": 2043,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "project-05": {
    "width": 2560,
    "height": 2043,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "project-06": {
    "width": 2043,
    "height": 2560,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "project-07": {
    "width": 2560,
    "height": 2560,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "project-08": {
    "width": 1920,
    "height": 2560,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "project-09": {
    "width": 2043,
    "height": 2560,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "project-10": {
    "width": 1440,
    "height": 2560,
    "widths": [
      480,
      960
    ]
  },
  "project-11": {
    "width": 2042,
    "height": 2560,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "project-12": {
    "width": 1500,
    "height": 2000,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "project-13": {
    "width": 1024,
    "height": 768,
    "widths": [
      480,
      960
    ]
  },
  "project-14": {
    "width": 768,
    "height": 1024,
    "widths": [
      480
    ]
  },
  "project-15": {
    "width": 768,
    "height": 1024,
    "widths": [
      480
    ]
  },
  "project-16": {
    "width": 768,
    "height": 1024,
    "widths": [
      480
    ]
  },
  "interior-01": {
    "width": 900,
    "height": 1600,
    "widths": [
      480
    ]
  },
  "interior-02": {
    "width": 1440,
    "height": 1800,
    "widths": [
      480,
      960
    ]
  },
  "interior-03": {
    "width": 1440,
    "height": 1800,
    "widths": [
      480,
      960
    ]
  },
  "interior-04": {
    "width": 1440,
    "height": 1800,
    "widths": [
      480,
      960
    ]
  },
  "interior-05": {
    "width": 900,
    "height": 1600,
    "widths": [
      480
    ]
  },
  "flooring-01": {
    "width": 900,
    "height": 1600,
    "widths": [
      480
    ]
  },
  "flooring-02": {
    "width": 900,
    "height": 1600,
    "widths": [
      480
    ]
  },
  "flooring-03": {
    "width": 1440,
    "height": 1800,
    "widths": [
      480,
      960
    ]
  },
  "remodeling-02": {
    "width": 1126,
    "height": 2000,
    "widths": [
      480,
      960
    ]
  },
  "co_ceo": {
    "width": 858,
    "height": 866,
    "widths": [
      480
    ]
  },
  "otoniel-santos-founder": {
    "width": 1080,
    "height": 1080,
    "widths": [
      400,
      800
    ]
  },
  "tonys-logo": {
    "width": 1187,
    "height": 317,
    "widths": [
      240,
      480
    ]
  },
  "elenardi-midia-logo": {
    "width": 1146,
    "height": 336,
    "widths": [
      100,
      200
    ]
  },
  "partners-logos": {
    "width": 600,
    "height": 140,
    "widths": []
  }
};
