#!/usr/bin/env python3
"""Generate deterministic responsive WebP variants and static metadata with Pillow.

Run from any directory. Originals remain unchanged; no runtime image fetching is
needed. Repeated runs avoid rewriting identical files and produce identical maps.
"""
import io
import json
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "public/images/r"


def write_if_changed(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or path.read_bytes() != content:
        path.write_bytes(content)


def main() -> None:
    photos = [f"project-{i:02}.jpg" for i in range(1, 17)]
    photos += [f"interior-{i:02}.jpg" for i in range(1, 6)]
    photos += [f"flooring-{i:02}.jpg" for i in range(1, 4)]
    photos += ["remodeling-02.jpg"]
    sources = [("photos", ROOT / "public/images" / name, [480, 960, 1440], False) for name in photos]
    sources += [
        ("co_ceo", ROOT / "public/images/co_ceo.png", [480, 960], False),
        ("founder", ROOT / "src/assets/otoniel-santos-founder.png", [400, 800], False),
        ("tonys-logo", ROOT / "src/assets/tonys-logo.png", [240, 480], True),
        ("elenardi-logo", ROOT / "src/assets/elenardi-midia-logo.png", [100, 200], True),
        ("partners", ROOT / "src/assets/partners-logos.png", [600], True),
    ]
    manifest = {}
    responsive_map = {}
    totals = {}
    OUTPUT.mkdir(parents=True, exist_ok=True)
    for group, source, widths, lossless in sources:
        if not source.is_file():
            raise FileNotFoundError(f"Required original missing: {source}")
        before, after = totals.get(group, (0, 0))
        before += source.stat().st_size
        with Image.open(source) as original:
            width, height = original.size
            manifest[source.stem] = {"width": width, "height": height}
            available = []
            image = original.convert("RGBA" if "A" in original.getbands() else "RGB")
            for target_width in widths:
                # Do not upscale or create equal-width variants.
                if target_width >= width:
                    continue
                target_height = max(1, round(height * target_width / width))
                resized = image.resize((target_width, target_height), Image.Resampling.LANCZOS)
                buffer = io.BytesIO()
                resized.save(buffer, format="WEBP", quality=82, method=6, lossless=lossless)
                content = buffer.getvalue()
                if group == "partners" and len(content) >= source.stat().st_size:
                    continue
                destination = OUTPUT / f"{source.stem}-{target_width}.webp"
                write_if_changed(destination, content)
                available.append(target_width)
                after += len(content)
            responsive_map[source.stem] = {"width": width, "height": height, "widths": available}
        totals[group] = (before, after)
    write_if_changed(OUTPUT / "manifest.json", (json.dumps(manifest, indent=2) + "\n").encode())
    typescript = "// Generated by scripts/make-responsive-images.py. Do not edit manually.\n"
    typescript += "export interface ResponsiveImageMetadata { width: number; height: number; widths: readonly number[] }\n"
    typescript += "export const responsiveMap: Readonly<Record<string, ResponsiveImageMetadata>> = "
    typescript += json.dumps(responsive_map, indent=2) + ";\n"
    write_if_changed(ROOT / "src/lib/responsiveMap.ts", typescript.encode())
    print("group | original bytes | all generated variant bytes")
    for group, (before, after) in totals.items():
        print(f"{group} | {before} | {after}")
    print(f"TOTAL | {sum(v[0] for v in totals.values())} | {sum(v[1] for v in totals.values())}")
    print("partners: no 600w variant when original width is <= 600 (no upscaling/equal-width variants).")


if __name__ == "__main__":
    main()