// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://ghznuutonacttnmqtiil.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdoem51dXRvbmFjdHRubXF0aWlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzczMTgwMzAsImV4cCI6MjA5Mjg5NDAzMH0.0CU9lBk2_elvHq71-j-qE2E5T8n_3-3uDIiPYmc9l4g';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
